// Generated by gencpp from file detection/reachedRequest.msg
// DO NOT EDIT!


#ifndef DETECTION_MESSAGE_REACHEDREQUEST_H
#define DETECTION_MESSAGE_REACHEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection
{
template <class ContainerAllocator>
struct reachedRequest_
{
  typedef reachedRequest_<ContainerAllocator> Type;

  reachedRequest_()
    {
    }
  reachedRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::detection::reachedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection::reachedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reachedRequest_

typedef ::detection::reachedRequest_<std::allocator<void> > reachedRequest;

typedef boost::shared_ptr< ::detection::reachedRequest > reachedRequestPtr;
typedef boost::shared_ptr< ::detection::reachedRequest const> reachedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection::reachedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection::reachedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detection::reachedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection::reachedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection::reachedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection::reachedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection::reachedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection::reachedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection::reachedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::detection::reachedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::detection::reachedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection/reachedRequest";
  }

  static const char* value(const ::detection::reachedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection::reachedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::detection::reachedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection::reachedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reachedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection::reachedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::detection::reachedRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_MESSAGE_REACHEDREQUEST_H
