# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from science/sensor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sensor(genpy.Message):
  _md5sum = "f03c616c12fbcd715e685d60bb04a3dc"
  _type = "science/sensor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 tsl_full
float32 lps_temp
float32 lps_pressure
float32 sht_humidity
float32 sht_temp
"""
  __slots__ = ['tsl_full','lps_temp','lps_pressure','sht_humidity','sht_temp']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tsl_full,lps_temp,lps_pressure,sht_humidity,sht_temp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sensor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tsl_full is None:
        self.tsl_full = 0.
      if self.lps_temp is None:
        self.lps_temp = 0.
      if self.lps_pressure is None:
        self.lps_pressure = 0.
      if self.sht_humidity is None:
        self.sht_humidity = 0.
      if self.sht_temp is None:
        self.sht_temp = 0.
    else:
      self.tsl_full = 0.
      self.lps_temp = 0.
      self.lps_pressure = 0.
      self.sht_humidity = 0.
      self.sht_temp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.tsl_full, _x.lps_temp, _x.lps_pressure, _x.sht_humidity, _x.sht_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.tsl_full, _x.lps_temp, _x.lps_pressure, _x.sht_humidity, _x.sht_temp,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.tsl_full, _x.lps_temp, _x.lps_pressure, _x.sht_humidity, _x.sht_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.tsl_full, _x.lps_temp, _x.lps_pressure, _x.sht_humidity, _x.sht_temp,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
