// Generated by gencpp from file traversal/move.msg
// DO NOT EDIT!


#ifndef TRAVERSAL_MESSAGE_MOVE_H
#define TRAVERSAL_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <traversal/moveRequest.h>
#include <traversal/moveResponse.h>


namespace traversal
{

struct move
{

typedef moveRequest Request;
typedef moveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move
} // namespace traversal


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traversal::move > {
  static const char* value()
  {
    return "7cef8d8112746dcd321eae0deeda86a8";
  }

  static const char* value(const ::traversal::move&) { return value(); }
};

template<>
struct DataType< ::traversal::move > {
  static const char* value()
  {
    return "traversal/move";
  }

  static const char* value(const ::traversal::move&) { return value(); }
};


// service_traits::MD5Sum< ::traversal::moveRequest> should match
// service_traits::MD5Sum< ::traversal::move >
template<>
struct MD5Sum< ::traversal::moveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traversal::move >::value();
  }
  static const char* value(const ::traversal::moveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traversal::moveRequest> should match
// service_traits::DataType< ::traversal::move >
template<>
struct DataType< ::traversal::moveRequest>
{
  static const char* value()
  {
    return DataType< ::traversal::move >::value();
  }
  static const char* value(const ::traversal::moveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traversal::moveResponse> should match
// service_traits::MD5Sum< ::traversal::move >
template<>
struct MD5Sum< ::traversal::moveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traversal::move >::value();
  }
  static const char* value(const ::traversal::moveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traversal::moveResponse> should match
// service_traits::DataType< ::traversal::move >
template<>
struct DataType< ::traversal::moveResponse>
{
  static const char* value()
  {
    return DataType< ::traversal::move >::value();
  }
  static const char* value(const ::traversal::moveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAVERSAL_MESSAGE_MOVE_H
