// Generated by gencpp from file sensors/Imu.msg
// DO NOT EDIT!


#ifndef SENSORS_MESSAGE_IMU_H
#define SENSORS_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensors
{
template <class ContainerAllocator>
struct Imu_
{
  typedef Imu_<ContainerAllocator> Type;

  Imu_()
    : yaw(0.0)
    , pitch(0.0)  {
    }
  Imu_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::sensors::Imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensors::Imu_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_

typedef ::sensors::Imu_<std::allocator<void> > Imu;

typedef boost::shared_ptr< ::sensors::Imu > ImuPtr;
typedef boost::shared_ptr< ::sensors::Imu const> ImuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensors::Imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensors::Imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensors::Imu_<ContainerAllocator1> & lhs, const ::sensors::Imu_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensors::Imu_<ContainerAllocator1> & lhs, const ::sensors::Imu_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensors

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensors::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::Imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::Imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::Imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::Imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensors::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19ef1e45577dac4da3eff04ddb600a22";
  }

  static const char* value(const ::sensors::Imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19ef1e45577dac4dULL;
  static const uint64_t static_value2 = 0xa3eff04ddb600a22ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensors::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensors/Imu";
  }

  static const char* value(const ::sensors::Imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensors::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n"
"float32 pitch\n"
;
  }

  static const char* value(const ::sensors::Imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensors::Imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensors::Imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensors::Imu_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSORS_MESSAGE_IMU_H
