// Generated by gencpp from file navigation/Planner_state.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_PLANNER_STATE_H
#define NAVIGATION_MESSAGE_PLANNER_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct Planner_state_
{
  typedef Planner_state_<ContainerAllocator> Type;

  Planner_state_()
    : status(0)  {
    }
  Planner_state_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int16_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::navigation::Planner_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::Planner_state_<ContainerAllocator> const> ConstPtr;

}; // struct Planner_state_

typedef ::navigation::Planner_state_<std::allocator<void> > Planner_state;

typedef boost::shared_ptr< ::navigation::Planner_state > Planner_statePtr;
typedef boost::shared_ptr< ::navigation::Planner_state const> Planner_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::Planner_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::Planner_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::Planner_state_<ContainerAllocator1> & lhs, const ::navigation::Planner_state_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::Planner_state_<ContainerAllocator1> & lhs, const ::navigation::Planner_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::Planner_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::Planner_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::Planner_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::Planner_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::Planner_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::Planner_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::Planner_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46fcc1fee3807f5925730339e5177777";
  }

  static const char* value(const ::navigation::Planner_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46fcc1fee3807f59ULL;
  static const uint64_t static_value2 = 0x25730339e5177777ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::Planner_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/Planner_state";
  }

  static const char* value(const ::navigation::Planner_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::Planner_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 status\n"
;
  }

  static const char* value(const ::navigation::Planner_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::Planner_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Planner_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::Planner_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::Planner_state_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_PLANNER_STATE_H
