// Generated by gencpp from file navigation/plan_state.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_PLAN_STATE_H
#define NAVIGATION_MESSAGE_PLAN_STATE_H

#include <ros/service_traits.h>


#include <navigation/plan_stateRequest.h>
#include <navigation/plan_stateResponse.h>


namespace navigation
{

struct plan_state
{

typedef plan_stateRequest Request;
typedef plan_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct plan_state
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::plan_state > {
  static const char* value()
  {
    return "b77f4b0588be197cccf2ef4c09a3fa03";
  }

  static const char* value(const ::navigation::plan_state&) { return value(); }
};

template<>
struct DataType< ::navigation::plan_state > {
  static const char* value()
  {
    return "navigation/plan_state";
  }

  static const char* value(const ::navigation::plan_state&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::plan_stateRequest> should match
// service_traits::MD5Sum< ::navigation::plan_state >
template<>
struct MD5Sum< ::navigation::plan_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::plan_state >::value();
  }
  static const char* value(const ::navigation::plan_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::plan_stateRequest> should match
// service_traits::DataType< ::navigation::plan_state >
template<>
struct DataType< ::navigation::plan_stateRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::plan_state >::value();
  }
  static const char* value(const ::navigation::plan_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::plan_stateResponse> should match
// service_traits::MD5Sum< ::navigation::plan_state >
template<>
struct MD5Sum< ::navigation::plan_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::plan_state >::value();
  }
  static const char* value(const ::navigation::plan_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::plan_stateResponse> should match
// service_traits::DataType< ::navigation::plan_state >
template<>
struct DataType< ::navigation::plan_stateResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::plan_state >::value();
  }
  static const char* value(const ::navigation::plan_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_PLAN_STATE_H
