// Generated by gencpp from file navigation/plan_stateRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_PLAN_STATEREQUEST_H
#define NAVIGATION_MESSAGE_PLAN_STATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct plan_stateRequest_
{
  typedef plan_stateRequest_<ContainerAllocator> Type;

  plan_stateRequest_()
    : pause(0)
    , contin(0)
    , rst(0)  {
    }
  plan_stateRequest_(const ContainerAllocator& _alloc)
    : pause(0)
    , contin(0)
    , rst(0)  {
  (void)_alloc;
    }



   typedef int8_t _pause_type;
  _pause_type pause;

   typedef int8_t _contin_type;
  _contin_type contin;

   typedef int8_t _rst_type;
  _rst_type rst;





  typedef boost::shared_ptr< ::navigation::plan_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::plan_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct plan_stateRequest_

typedef ::navigation::plan_stateRequest_<std::allocator<void> > plan_stateRequest;

typedef boost::shared_ptr< ::navigation::plan_stateRequest > plan_stateRequestPtr;
typedef boost::shared_ptr< ::navigation::plan_stateRequest const> plan_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::plan_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::plan_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::plan_stateRequest_<ContainerAllocator1> & lhs, const ::navigation::plan_stateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pause == rhs.pause &&
    lhs.contin == rhs.contin &&
    lhs.rst == rhs.rst;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::plan_stateRequest_<ContainerAllocator1> & lhs, const ::navigation::plan_stateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::plan_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::plan_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::plan_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::plan_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::plan_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::plan_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::plan_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3784a326caf7609ed9090b60e51420a0";
  }

  static const char* value(const ::navigation::plan_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3784a326caf7609eULL;
  static const uint64_t static_value2 = 0xd9090b60e51420a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::plan_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/plan_stateRequest";
  }

  static const char* value(const ::navigation::plan_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::plan_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 pause\n"
"int8 contin\n"
"int8 rst\n"
;
  }

  static const char* value(const ::navigation::plan_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::plan_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pause);
      stream.next(m.contin);
      stream.next(m.rst);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct plan_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::plan_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::plan_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "pause: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pause);
    s << indent << "contin: ";
    Printer<int8_t>::stream(s, indent + "  ", v.contin);
    s << indent << "rst: ";
    Printer<int8_t>::stream(s, indent + "  ", v.rst);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_PLAN_STATEREQUEST_H
